import type { DataType, Expression, Program, SourceSpan, Statement, Target, Parameter } from '../language/ast';
export interface TraceStep { line:number; variables:Record<string,unknown>; output:string[]; label:string; }
export interface RunResult { output:string[]; variables:Record<string,unknown>; coverage:number[]; trace:TraceStep[]; steps:number; }
export class RuntimeError extends Error { constructor(message:string,public line:number,public code='runtime'){super(message);this.name='RuntimeError';} }
export class MissingInputError extends Error { constructor(public variable:string,public dataType:DataType,public line:number){super(`Enter a value for ${variable} (${dataType}).`);this.name='MissingInputError';} }
const ROUTINES=new Set(['DIV','MOD','ROUND','LENGTH','SUBSTRING','UCASE','LCASE','UPPER','LOWER','RANDOM']);
type Routine={parameters:Parameter[];body:Statement[];returnType?:DataType};
class ReturnSignal { constructor(public value:unknown){} }
class Interpreter { private values:Record<string,unknown>={}; private types:Record<string,DataType>={}; private constants=new Set<string>(); private arrays:Record<string,unknown>={}; private routines:Record<string,Routine>={}; private files:Record<string,string[]>={}; private openFile:string|null=null; private output:string[]=[]; private trace:TraceStep[]=[]; private coverage=new Set<number>(); private steps=0; private inputPosition=0; constructor(private readonly inputs:string[],private readonly limit=10000){}
 run(program:Program):RunResult { for(const s of program.statements) if(s.kind==='Procedure'||s.kind==='Function')this.routines[s.name.toUpperCase()]={parameters:s.parameters,body:s.body,returnType:s.kind==='Function'?s.returnType:undefined}; this.executeBlock(program.statements.filter(s=>s.kind!=='Procedure'&&s.kind!=='Function')); return{output:this.output,variables:{...this.values,...this.arrays},coverage:[...this.coverage].sort((a,b)=>a-b),trace:this.trace,steps:this.steps}; }
 private executeBlock(st:Statement[]):void{for(const s of st)this.execute(s);}
 private tick(n:SourceSpan,label:string){if(++this.steps>this.limit)throw new RuntimeError(`Execution stopped after ${this.limit.toLocaleString()} steps. Check your loop.`,n.line,'step-limit');this.coverage.add(n.line);this.trace.push({line:n.line,variables:{...this.values,...this.arrays},output:[...this.output],label});}
 private execute(s:Statement):void{this.tick(s,s.kind.replace(/([A-Z])/g,' $1').trim());try{switch(s.kind){case'Declaration':if(Object.hasOwn(this.values,s.name)||Object.hasOwn(this.arrays,s.name))throw new RuntimeError(`${s.name} has already been declared.`,s.line);this.types[s.name]=s.dataType;if(s.array){this.arrays[s.name]=this.makeArray(s.array.bounds); }else this.values[s.name]=null;return;case'Constant':this.requireNameFree(s.name,s.line);this.values[s.name]=this.evaluate(s.value);this.constants.add(s.name);return;case'Assignment':this.setTarget(s.target,this.evaluate(s.value),s.line);return;case'Input':{const name=s.target.name;this.requireName(name,s.line);if(this.inputPosition>=this.inputs.length)throw new MissingInputError(name,this.types[name]??'STRING',s.line);this.setTarget(s.target,this.convertInput(this.inputs[this.inputPosition++]!,this.types[name]??'STRING',s.line),s.line);return;}case'Output':this.output.push(s.expressions.map(e=>this.format(this.evaluate(e))).join(' '));return;case'IfStatement':this.executeBlock(this.truthy(this.evaluate(s.condition))?s.thenBody:s.elseBody);return;case'WhileStatement':{let g=0;while(this.truthy(this.evaluate(s.condition))){if(++g>this.limit)throw new RuntimeError('This WHILE loop is taking too long.',s.line,'loop-limit');this.executeBlock(s.body);}return;}case'ForStatement':{this.requireName(s.name,s.line);const first=Number(this.evaluate(s.start)),last=Number(this.evaluate(s.end)),step=s.step?Number(this.evaluate(s.step)):1;if(step===0)throw new RuntimeError('A FOR STEP cannot be zero.',s.line);for(let v=first;step>0?v<=last:v>=last;v+=step){this.values[s.name]=v;this.executeBlock(s.body);}return;}case'RepeatStatement':{let g=0;do{if(++g>this.limit)throw new RuntimeError('This REPEAT loop is taking too long.',s.line,'loop-limit');this.executeBlock(s.body);}while(!this.truthy(this.evaluate(s.condition)));return;}case'CaseStatement':{const target=this.evaluate(s.expression);const branch=s.branches.find(b=>b.selectors.some(x=>this.evaluate(x)===target));this.executeBlock(branch?.body??s.otherwise);return;}case'CallStatement':this.callRoutine(s.name,s.arguments,s.line);return;case'ReturnStatement':throw new ReturnSignal(s.value?this.evaluate(s.value):null);case'FileStatement':this.fileOp(s);return;}}
 catch(e){if(e instanceof ReturnSignal)throw e;throw e;}}
 private callRoutine(name:string,args:Expression[],line:number):unknown{const r=this.routines[name.toUpperCase()];if(!r)throw new RuntimeError(`${name} has not been declared as a procedure or function.`,line,'routine');if(args.length!==r.parameters.length)throw new RuntimeError(`${name} expects ${r.parameters.length} parameter${r.parameters.length===1?'':'s'}.`,line);const oldV=this.values,oldT=this.types,oldC=this.constants;this.values={...this.values};this.types={...this.types};this.constants=new Set(this.constants);try{r.parameters.forEach((p,i)=>{this.types[p.name]=p.dataType;this.values[p.name]=this.evaluate(args[i]!);});this.executeBlock(r.body);return null;}catch(e){if(e instanceof ReturnSignal)return e.value;throw e;}finally{this.values=oldV;this.types=oldT;this.constants=oldC;}}
 private fileOp(s:any){if(s.operation==='OPEN'){const fileName=String(s.name);this.openFile=fileName;if(!this.files[fileName])this.files[fileName]=[];return;}if(s.operation==='CLOSE'){this.openFile=null;return;}if(!this.openFile)throw new RuntimeError('Open a file before using file operations.',s.line);if(s.operation==='WRITE'){this.files[this.openFile]!.push(this.format(this.evaluate(s.value)));return;}const lines=this.files[this.openFile]!,raw=lines.shift()??'';const name=s.target.name;this.setTarget(s.target,this.convertInput(raw,this.types[name]??'STRING',s.line),s.line);}
 private makeArray(bounds:{start:number;end:number}[]):unknown{if(bounds.length===1)return Array.from({length:bounds[0]!.end-bounds[0]!.start+1},()=>null);return Array.from({length:bounds[0]!.end-bounds[0]!.start+1},()=>this.makeArray(bounds.slice(1)));}
 private getTarget(t:Target){this.requireName(t.name,t.line);let v=t.indexes.length?this.arrays[t.name]:this.values[t.name];for(const x of t.indexes){const i=Number(this.evaluate(x));v=(v as unknown[])[i-1];}return v;}
 private setTarget(t:Target,value:unknown,line:number){this.requireName(t.name,line);if(!t.indexes.length){if(this.constants.has(t.name))throw new RuntimeError(`${t.name} is a CONSTANT and cannot be changed.`,line);this.ensureValueType(value,this.types[t.name]??'STRING',line,t.name);this.values[t.name]=value;return;}let v=this.arrays[t.name] as unknown[];t.indexes.slice(0,-1).forEach(x=>v=v[Number(this.evaluate(x))-1] as unknown[]);v[Number(this.evaluate(t.indexes.at(-1)!))-1]=value;}
 private ensureValueType(value:unknown,type:DataType,line:number,name:string){const valid=type==='INTEGER'?typeof value==='number'&&Number.isInteger(value):type==='REAL'?typeof value==='number'&&Number.isFinite(value):type==='CHAR'?typeof value==='string'&&value.length===1:type==='BOOLEAN'?typeof value==='boolean':typeof value==='string';if(!valid)throw new RuntimeError(`Cannot assign ${this.format(value)} to ${name} (${type}).`,line,'type');}
 private requireName(n:string,line:number){if(!Object.hasOwn(this.values,n)&&!Object.hasOwn(this.arrays,n))throw new RuntimeError(`${n} has not been declared. Add DECLARE ${n} before using it.`,line,'name');}
 private requireNameFree(n:string,line:number){if(Object.hasOwn(this.values,n)||Object.hasOwn(this.arrays,n))throw new RuntimeError(`${n} has already been declared.`,line);}
 private convertInput(raw:string,type:DataType,line:number):unknown{const v=raw.trim();if(type==='INTEGER'){if(!/^[+-]?\d+$/.test(v))throw new RuntimeError(`“${raw}” is not an INTEGER.`,line);return Number(v);}if(type==='REAL'){if(!Number.isFinite(Number(v)))throw new RuntimeError(`“${raw}” is not a REAL number.`,line);return Number(v);}if(type==='CHAR'){if(raw.length!==1)throw new RuntimeError('CHAR input needs exactly one character.',line);return raw;}if(type==='BOOLEAN'){if(/^TRUE$/i.test(v))return true;if(/^FALSE$/i.test(v))return false;throw new RuntimeError('BOOLEAN input must be TRUE or FALSE.',line);}return raw;}
 private evaluate(e:Expression):unknown{switch(e.kind){case'NumberLiteral':case'StringLiteral':case'BooleanLiteral':return e.value;case'Variable':this.requireName(e.name,e.line);if(this.values[e.name]===null)throw new RuntimeError(`${e.name} has been declared but does not have a value yet.`,e.line);return this.values[e.name];case'ArrayAccess':return this.getTarget(e);case'UnaryExpression':return e.operator==='NOT'?!this.truthy(this.evaluate(e.operand)):-Number(this.evaluate(e.operand));case'BinaryExpression':return this.binary(e.operator,e.left,e.right,e.line);case'CallExpression':return ROUTINES.has(e.name)?this.call(e.name,e.arguments,e.line):this.callRoutine(e.name,e.arguments,e.line);}}
 private binary(op:string,a:Expression,b:Expression,line:number){const l=this.evaluate(a);if(op==='AND'&&!this.truthy(l))return false;if(op==='OR'&&this.truthy(l))return true;const r=this.evaluate(b);switch(op){case'+':return typeof l==='string'||typeof r==='string'?String(l)+String(r):Number(l)+Number(r);case'-':return Number(l)-Number(r);case'*':return Number(l)*Number(r);case'/':if(Number(r)===0)throw new RuntimeError('You cannot divide by zero.',line);return Number(l)/Number(r);case'DIV':if(Number(r)===0)throw new RuntimeError('You cannot divide by zero.',line);return Math.floor(Number(l)/Number(r));case'MOD':if(Number(r)===0)throw new RuntimeError('You cannot use MOD with zero.',line);return Number(l)%Number(r);case'^':return Number(l)**Number(r);case'=':return l===r;case'<>':case'!=':return l!==r;case'<':return(l as number)<(r as number);case'<=':return(l as number)<=(r as number);case'>':return(l as number)>(r as number);case'>=':return(l as number)>=(r as number);case'AND':return this.truthy(l)&&this.truthy(r);case'OR':return this.truthy(l)||this.truthy(r);default:throw new RuntimeError(`The operator ${op} is not supported.`,line);}}
 private call(name:string,args:Expression[],line:number){const v=args.map(a=>this.evaluate(a));const need=(n:number)=>{if(v.length!==n)throw new RuntimeError(`${name}() takes ${n} argument${n===1?'':'s'}.`,line);};switch(name){case'DIV':need(2);if(Number(v[1])===0)throw new RuntimeError('You cannot divide by zero.',line);return Math.floor(Number(v[0])/Number(v[1]));case'MOD':need(2);return Number(v[0])%Number(v[1]);case'ROUND':if(v.length<1||v.length>2)throw new RuntimeError('ROUND() takes one or two arguments.',line);return roundLikePython(Number(v[0]),v.length===2?Number(v[1]):0);case'LENGTH':need(1);return String(v[0]).length;case'UCASE':case'UPPER':need(1);return String(v[0]).toUpperCase();case'LCASE':case'LOWER':need(1);return String(v[0]).toLowerCase();case'SUBSTRING':need(3);return String(v[0]).substring(Number(v[1])-1,Number(v[1])-1+Number(v[2]));case'RANDOM':need(0);return Math.random();}}
 private truthy(v:unknown){return Boolean(v);} private format(v:unknown){return v===true?'TRUE':v===false?'FALSE':String(v);}}
export function execute(program:Program,inputs:string[]=[]):RunResult{return new Interpreter(inputs).run(program);}
function roundLikePython(value:number,places:number){const f=10**Math.max(-100,Math.min(100,places)),s=value*f,l=Math.floor(s),frac=s-l,t=Number.EPSILON*Math.max(1,Math.abs(s))*4,r=Math.abs(frac-.5)<=t?(l%2===0?l:l+1):Math.round(s);return r/f;}
