import type { DataType, Expression, FileStatement, Program, Statement, Target } from './ast';

/** Compile a validated Pico program to readable, standalone Python 3 source. */
export function compileToPython(program: Program): string {
  const generator = new PythonGenerator();
  return generator.generate(program);
}

class PythonGenerator {
  private readonly lines: string[] = [];
  private indent = 0;
  private readonly types = new Map<string, DataType>();

  generate(program: Program): string {
    this.lines.push('# Generated by Pico — Python 3');
    this.lines.push('import random as _random');
    this.lines.push('');
    this.lines.push(...HELPERS);
    this.lines.push('');
    for (const statement of program.statements) {
      if (statement.kind === 'Declaration') this.types.set(statement.name, statement.dataType);
    }
    for (const statement of program.statements) {
      if (statement.kind === 'Procedure' || statement.kind === 'Function') this.emitRoutine(statement);
    }
    const executable = program.statements.filter((statement) => statement.kind !== 'Procedure' && statement.kind !== 'Function');
    if (executable.length) {
      this.emit('@_pico_main');
      this.emit('def _pico_program():');
      this.indent++;
      for (const statement of executable) this.emitStatement(statement);
      if (!executable.some((statement) => statement.kind === 'ReturnStatement')) this.emit('pass', false);
      this.indent--;
      this.emit('');
      this.emit('_pico_program()');
    }
    return `${this.lines.join('\n')}\n`;
  }

  private emitRoutine(statement: Extract<Statement, { kind: 'Procedure' | 'Function' }>): void {
    const parameters = statement.parameters.map((parameter) => parameter.name).join(', ');
    this.emit(`def ${statement.name}(${parameters}):`);
    this.indent++;
    for (const parameter of statement.parameters) this.types.set(parameter.name, parameter.dataType);
    for (const bodyStatement of statement.body) this.emitStatement(bodyStatement);
    if (!statement.body.length || !statement.body.some((item) => item.kind === 'ReturnStatement')) this.emit('pass', false);
    this.indent--;
    this.emit('');
  }

  private emitStatement(statement: Statement): void {
    switch (statement.kind) {
      case 'Declaration':
        if (statement.array) {
          const bounds = statement.array.bounds.map((bound) => `[${bound.start}, ${bound.end}]`).join(', ');
          this.emit(`${statement.name} = _PicoArray([${bounds}])`);
        } else this.emit(`${statement.name} = None`);
        this.types.set(statement.name, statement.dataType);
        break;
      case 'Constant':
        this.emit(`${statement.name} = ${this.expression(statement.value)}`);
        break;
      case 'Assignment':
        this.emit(`${this.target(statement.target)} = ${this.expression(statement.value)}`);
        break;
      case 'Input': {
        const type = this.types.get(statement.target.name) ?? 'STRING';
        this.emit(`${this.target(statement.target)} = _pico_input(${JSON.stringify(type)}, ${JSON.stringify(statement.target.name)})`);
        break;
      }
      case 'Output':
        this.emit(`print(${statement.expressions.map((expression) => `_pico_format(${this.expression(expression)})`).join(', ')}, sep='')`);
        break;
      case 'IfStatement':
        this.emit(`if ${this.expression(statement.condition)}:`);
        this.emitBody(statement.thenBody);
        if (statement.elseBody.length) {
          this.emit('else:');
          this.emitBody(statement.elseBody);
        }
        break;
      case 'WhileStatement':
        this.emit(`while ${this.expression(statement.condition)}:`);
        this.emitBody(statement.body);
        break;
      case 'ForStatement':
        this.emit(`for ${statement.name} in _pico_range(${this.expression(statement.start)}, ${this.expression(statement.end)}, ${statement.step ? this.expression(statement.step) : '1'}):`);
        this.emitBody(statement.body);
        break;
      case 'RepeatStatement':
        this.emit('while True:');
        this.emitBody(statement.body);
        this.emit(`if ${this.expression(statement.condition)}: break`);
        break;
      case 'CaseStatement':
        statement.branches.forEach((branch, index) => {
          const keyword = index === 0 ? 'if' : 'elif';
          this.emit(`${keyword} ${' or '.repeat(0)}${branch.selectors.map((selector) => `${this.expression(statement.expression)} == ${this.expression(selector)}`).join(' or ')}:`);
          this.emitBody(branch.body);
        });
        if (statement.otherwise.length) {
          this.emit('else:');
          this.emitBody(statement.otherwise);
        }
        break;
      case 'CallStatement':
        this.emit(`${statement.name}(${statement.arguments.map((argument) => this.expression(argument)).join(', ')})`);
        break;
      case 'ReturnStatement':
        this.emit(`return${statement.value ? ` ${this.expression(statement.value)}` : ''}`);
        break;
      case 'Procedure':
      case 'Function':
        break;
      case 'FileStatement':
        this.emitFile(statement);
        break;
    }
  }

  private emitFile(statement: FileStatement): void {
    if (statement.operation === 'OPEN') this.emit(`_pico_files[${JSON.stringify(statement.name ?? '')}] = open(${JSON.stringify(statement.name ?? '')}, ${JSON.stringify(statement.mode === 'WRITE' ? 'w' : 'r')}, encoding='utf-8')`);
    else if (statement.operation === 'CLOSE') this.emit(`_pico_files.get(${JSON.stringify(statement.name ?? '')}, None) and _pico_files[${JSON.stringify(statement.name ?? '')}].close()`);
    else if (statement.operation === 'READ') this.emit(`${this.target(statement.target!)} = _pico_files[${JSON.stringify(statement.name ?? '')}].readline().rstrip('\\n')`);
    else if (statement.operation === 'WRITE') this.emit(`_pico_files[${JSON.stringify(statement.name ?? '')}].write(_pico_format(${this.expression(statement.value!)}))`);
  }

  private emitBody(body: Statement[]): void {
    this.indent++;
    if (body.length) for (const statement of body) this.emitStatement(statement);
    else this.emit('pass', false);
    this.indent--;
  }

  private target(target: Target): string {
    return target.indexes.length ? `${target.name}[${target.indexes.map((index) => this.expression(index)).join(', ')}]` : target.name;
  }

  private expression(expression: Expression): string {
    switch (expression.kind) {
      case 'NumberLiteral': return expression.raw;
      case 'StringLiteral': return JSON.stringify(expression.value);
      case 'BooleanLiteral': return expression.value ? 'True' : 'False';
      case 'Variable': return expression.name;
      case 'ArrayAccess': return `${expression.name}[${expression.indexes.map((index) => this.expression(index)).join(', ')}]`;
      case 'UnaryExpression': return expression.operator === 'NOT' ? `(not ${this.expression(expression.operand)})` : `(-${this.expression(expression.operand)})`;
      case 'BinaryExpression': {
        const operator = expression.operator === 'AND' ? 'and' : expression.operator === 'OR' ? 'or' : expression.operator === '<>' ? '!=' : expression.operator === 'DIV' ? '//' : expression.operator === '^' ? '**' : expression.operator;
        return `(${this.expression(expression.left)} ${operator} ${this.expression(expression.right)})`;
      }
      case 'CallExpression': return this.call(expression.name, expression.arguments.map((argument) => this.expression(argument)));
    }
  }

  private call(name: string, args: string[]): string {
    const upper = name.toUpperCase();
    const builtins: Record<string, string> = { DIV: '_pico_div', MOD: '_pico_mod', ROUND: 'round', LENGTH: 'len', SUBSTRING: '_pico_substring', UCASE: 'str.upper', LCASE: 'str.lower', UPPER: 'str.upper', LOWER: 'str.lower', RANDOM: '_random.random' };
    if (upper === 'UCASE' || upper === 'LCASE' || upper === 'UPPER' || upper === 'LOWER') return `${builtins[upper]}(${args[0]})`;
    return `${builtins[upper] ?? name}(${args.join(', ')})`;
  }

  private emit(line: string, indent = true): void {
    this.lines.push(`${indent ? '    '.repeat(this.indent) : ''}${line}`);
  }
}

const HELPERS = [
  'class _PicoArray:',
  '    def __init__(self, bounds):',
  '        self.bounds = bounds',
  '        def make(d): return [make(d[1:]) for _ in range(d[0][1] - d[0][0] + 1)] if d else None',
  '        self.values = make(bounds)',
  '    def _index(self, index, dimension):',
  '        start, end = self.bounds[dimension]',
  '        if not isinstance(index, int) or not start <= index <= end: raise IndexError("ARRAY index out of range")',
  '        return index - start',
  '    def __getitem__(self, indexes):',
  '        indexes = indexes if isinstance(indexes, tuple) else (indexes,)',
  '        value = self.values',
  '        for dimension, index in enumerate(indexes): value = value[self._index(index, dimension)]',
  '        return value',
  '    def __setitem__(self, indexes, value):',
  '        indexes = indexes if isinstance(indexes, tuple) else (indexes,)',
  '        target = self.values',
  '        for dimension, index in enumerate(indexes[:-1]): target = target[self._index(index, dimension)]',
  '        target[self._index(indexes[-1], len(indexes) - 1)] = value',
  '',
  '_pico_files = {}',
  'def _pico_format(value):',
  '    if value is True: return "TRUE"',
  '    if value is False: return "FALSE"',
  '    return str(value)',
  'def _pico_input(type_name, variable):',
  '    text = input()',
  '    if type_name == "INTEGER":',
  '        if not text.strip().lstrip("+-").isdigit(): raise ValueError(f"{text!r} is not an INTEGER.")',
  '        return int(text)',
  '    if type_name == "REAL":',
  '        if not __import__("re").fullmatch(r"[+-]?\\d+\\.\\d+", text.strip()): raise ValueError(f"{text!r} is not a REAL number; use a decimal such as 5.0.")',
  '        return float(text)',
  '    if type_name == "BOOLEAN":',
  '        if text.strip().upper() == "TRUE": return True',
  '        if text.strip().upper() == "FALSE": return False',
  '        raise ValueError("BOOLEAN input must be TRUE or FALSE.")',
  '    return text if type_name == "STRING" else (text if len(text) == 1 else (_ for _ in ()).throw(ValueError("CHAR input needs one character.")))',
  'def _pico_range(start, end, step):',
  '    if step == 0: raise ValueError("FOR STEP cannot be zero")',
  '    return range(start, end + (1 if step > 0 else -1), step)',
  'def _pico_div(a, b): return a // b',
  'def _pico_mod(a, b): return a % b',
  'def _pico_substring(text, start, length): return list(text)[start - 1:start - 1 + length] if isinstance(text, list) else text[start - 1:start - 1 + length]',
  'def _pico_main(function): return function',
];
